name: bmadx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipython
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - numpy
  - matplotlib
  - pytest
  - numba
  - numdifftools
  - kornia
  - bmad
  - pytao
  - distgen
  